require("config.lsp.jdtls").setup()
-- local config = {
-- 	cmd = {
-- 		"/home/max/.local/share/nvim/mason/bin/jdtls",
-- 		"-configuration",
-- 		"/home/max/.cache/jdtls/config",
-- 		"-data",
-- 		"/home/max/.cache/jdtls/workspace/",
-- 	},
-- 	root_dir = vim.fs.dirname(vim.fs.find({ "gradlew", ".git", "mvnw" }, { upward = true })[1]),
-- }
-- require("jdtls").start_or_attach(config)
